# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dupe}
  s.version = "0.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Parker"]
  s.date = %q{2010-04-05}
  s.description = %q{Dupe rides on top of ActiveResource to allow you to cuke the client side of 
                           a service-oriented app without having to worry about whether or not the service 
                           is live or available while cuking.}
  s.email = %q{moonmaster9000@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "lib/dupe.rb",
     "lib/dupe/active_resource_extensions.rb",
     "lib/dupe/attribute_template.rb",
     "lib/dupe/cucumber_hooks.rb",
     "lib/dupe/custom_mocks.rb",
     "lib/dupe/database.rb",
     "lib/dupe/dupe.rb",
     "lib/dupe/hash_pruner.rb",
     "lib/dupe/log.rb",
     "lib/dupe/mock.rb",
     "lib/dupe/model.rb",
     "lib/dupe/network.rb",
     "lib/dupe/record.rb",
     "lib/dupe/rest_validation.rb",
     "lib/dupe/schema.rb",
     "lib/dupe/sequence.rb",
     "lib/dupe/singular_plural_detection.rb",
     "lib/dupe/string.rb",
     "lib/dupe/symbol.rb",
     "rails_generators/dupe/dupe_generator.rb",
     "rails_generators/dupe/templates/custom_mocks.rb",
     "rails_generators/dupe/templates/definitions.rb",
     "rails_generators/dupe/templates/load_dupe.rb"
  ]
  s.homepage = %q{http://github.com/moonmaster9000/dupe}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A tool that helps you mock services while cuking.}
  s.test_files = [
    "spec/lib_specs/log_spec.rb",
     "spec/lib_specs/symbol_spec.rb",
     "spec/lib_specs/database_spec.rb",
     "spec/lib_specs/logged_request_spec.rb",
     "spec/lib_specs/rest_validation_spec.rb",
     "spec/lib_specs/schema_spec.rb",
     "spec/lib_specs/dupe_spec.rb",
     "spec/lib_specs/network_spec.rb",
     "spec/lib_specs/model_spec.rb",
     "spec/lib_specs/sequence_spec.rb",
     "spec/lib_specs/string_spec.rb",
     "spec/lib_specs/hash_pruner_spec.rb",
     "spec/lib_specs/record_spec.rb",
     "spec/lib_specs/mock_spec.rb",
     "spec/lib_specs/attribute_template_spec.rb",
     "spec/lib_specs/mock_definitions_spec.rb",
     "spec/lib_specs/active_resource_extensions_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activeresource>, ["~> 3.0.0"])
    else
      s.add_dependency(%q<activeresource>, ["~> 3.0.0"])
    end
  else
    s.add_dependency(%q<activeresource>, ["~> 3.0.0"])
  end
end

