$LOAD_PATH << './lib'
# require 'rubygems'
# gem 'activeresource'
# gem 'rspec'
require 'rubygems'
gem 'activeresource'
gem 'rspec'
gem 'cucumber'
require 'cucumber'
require 'activeresource'
require 'dupe'
